### ISSUE TITLE
Change payment error type

### ISSUE THREAD

**Issue by edwardbrowncross** [welldigital/braintree-go#5]
The confirm function should return the Braintree custom error type (`braintree.BraintreeError`) for errors, populated with as much information as possible, so that we can create better error responses from the pharmacy API

**Comment by Rhymond** [comment]
@edwardbrowncross I scanned whole braintree-go library and it looks like they're using BraintreeError type only to return HTTP errors. in confirm function `tr.execute` returns `response, BraintreeError`. Other, internal errors are default `error` type. Do you still want to use BraintreeError to handle internal errors. e.g. `can't parse query`

**Comment by edwardbrowncross** [comment]
That's a good point. I think my original issue was a bit confused.

The reasoning behind this is to be able to distinguish between internal errors (we will replace the error with our own generic error message) and errors caused by the user's financial situation (we will pass the error message to the user verbatim for them to respond to).

So confirm should return an `error` type/interface. If the error is due to `execute`, then it should return the braintree error type, which it already does!

I will close this issue.
